// flow-typed signature: 934482c5288972293feb247224722c68
// flow-typed version: <<STUB>>/electron-canvas-to-buffer_vhttps://github.com/lambrou/electron-canvas-to-buffer.git/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'electron-canvas-to-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'electron-canvas-to-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'electron-canvas-to-buffer/example/write' {
  declare module.exports: any;
}

declare module 'electron-canvas-to-buffer/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'electron-canvas-to-buffer/example/write.js' {
  declare module.exports: $Exports<'electron-canvas-to-buffer/example/write'>;
}
declare module 'electron-canvas-to-buffer/index' {
  declare module.exports: $Exports<'electron-canvas-to-buffer'>;
}
declare module 'electron-canvas-to-buffer/index.js' {
  declare module.exports: $Exports<'electron-canvas-to-buffer'>;
}
declare module 'electron-canvas-to-buffer/test.js' {
  declare module.exports: $Exports<'electron-canvas-to-buffer/test'>;
}
