// flow-typed signature: 3d614c4c3cadbe39515f47f8b00b86a9
// flow-typed version: <<STUB>>/fetch-defaults_v^1.0.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-defaults'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-defaults' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-defaults/test/fetch' {
  declare module.exports: any;
}

declare module 'fetch-defaults/test/index_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-defaults/index' {
  declare module.exports: $Exports<'fetch-defaults'>;
}
declare module 'fetch-defaults/index.js' {
  declare module.exports: $Exports<'fetch-defaults'>;
}
declare module 'fetch-defaults/test/fetch.js' {
  declare module.exports: $Exports<'fetch-defaults/test/fetch'>;
}
declare module 'fetch-defaults/test/index_test.js' {
  declare module.exports: $Exports<'fetch-defaults/test/index_test'>;
}
