// flow-typed signature: d7bc338007bd5a15d5aeb3104a85c939
// flow-typed version: <<STUB>>/file-system_v^2.2.2/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'file-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'file-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'file-system/file-system' {
  declare module.exports: any;
}

declare module 'file-system/Gruntfile' {
  declare module.exports: any;
}

declare module 'file-system/test/copy' {
  declare module.exports: any;
}

declare module 'file-system/test/copyFile' {
  declare module.exports: any;
}

declare module 'file-system/test/filter' {
  declare module.exports: any;
}

declare module 'file-system/test/fs' {
  declare module.exports: any;
}

declare module 'file-system/test/mkdir' {
  declare module.exports: any;
}

declare module 'file-system/test/recurse' {
  declare module.exports: any;
}

// Filename aliases
declare module 'file-system/file-system.js' {
  declare module.exports: $Exports<'file-system/file-system'>;
}
declare module 'file-system/Gruntfile.js' {
  declare module.exports: $Exports<'file-system/Gruntfile'>;
}
declare module 'file-system/test/copy.js' {
  declare module.exports: $Exports<'file-system/test/copy'>;
}
declare module 'file-system/test/copyFile.js' {
  declare module.exports: $Exports<'file-system/test/copyFile'>;
}
declare module 'file-system/test/filter.js' {
  declare module.exports: $Exports<'file-system/test/filter'>;
}
declare module 'file-system/test/fs.js' {
  declare module.exports: $Exports<'file-system/test/fs'>;
}
declare module 'file-system/test/mkdir.js' {
  declare module.exports: $Exports<'file-system/test/mkdir'>;
}
declare module 'file-system/test/recurse.js' {
  declare module.exports: $Exports<'file-system/test/recurse'>;
}
