// flow-typed signature: 909871523c7449cc48e4fd5c7438d22b
// flow-typed version: <<STUB>>/gps_v^0.5.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gps'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gps' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gps/examples/confluence' {
  declare module.exports: any;
}

declare module 'gps/examples/dashboard/server' {
  declare module.exports: any;
}

declare module 'gps/examples/fileRead' {
  declare module.exports: any;
}

declare module 'gps/examples/fileWrite' {
  declare module.exports: any;
}

declare module 'gps/examples/json-stream' {
  declare module.exports: any;
}

declare module 'gps/examples/maps/server' {
  declare module.exports: any;
}

declare module 'gps/examples/serial' {
  declare module.exports: any;
}

declare module 'gps/examples/set-date' {
  declare module.exports: any;
}

declare module 'gps/examples/simple' {
  declare module.exports: any;
}

declare module 'gps/examples/state' {
  declare module.exports: any;
}

declare module 'gps/gps' {
  declare module.exports: any;
}

declare module 'gps/gps.min' {
  declare module.exports: any;
}

declare module 'gps/tests/functions' {
  declare module.exports: any;
}

declare module 'gps/tests/parser' {
  declare module.exports: any;
}

declare module 'gps/tests/partial' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gps/examples/confluence.js' {
  declare module.exports: $Exports<'gps/examples/confluence'>;
}
declare module 'gps/examples/dashboard/server.js' {
  declare module.exports: $Exports<'gps/examples/dashboard/server'>;
}
declare module 'gps/examples/fileRead.js' {
  declare module.exports: $Exports<'gps/examples/fileRead'>;
}
declare module 'gps/examples/fileWrite.js' {
  declare module.exports: $Exports<'gps/examples/fileWrite'>;
}
declare module 'gps/examples/json-stream.js' {
  declare module.exports: $Exports<'gps/examples/json-stream'>;
}
declare module 'gps/examples/maps/server.js' {
  declare module.exports: $Exports<'gps/examples/maps/server'>;
}
declare module 'gps/examples/serial.js' {
  declare module.exports: $Exports<'gps/examples/serial'>;
}
declare module 'gps/examples/set-date.js' {
  declare module.exports: $Exports<'gps/examples/set-date'>;
}
declare module 'gps/examples/simple.js' {
  declare module.exports: $Exports<'gps/examples/simple'>;
}
declare module 'gps/examples/state.js' {
  declare module.exports: $Exports<'gps/examples/state'>;
}
declare module 'gps/gps.js' {
  declare module.exports: $Exports<'gps/gps'>;
}
declare module 'gps/gps.min.js' {
  declare module.exports: $Exports<'gps/gps.min'>;
}
declare module 'gps/tests/functions.js' {
  declare module.exports: $Exports<'gps/tests/functions'>;
}
declare module 'gps/tests/parser.js' {
  declare module.exports: $Exports<'gps/tests/parser'>;
}
declare module 'gps/tests/partial.js' {
  declare module.exports: $Exports<'gps/tests/partial'>;
}
