// flow-typed signature: 1ac5e1e88895ff521341dcec179053d8
// flow-typed version: <<STUB>>/react-closeable-tabs_v^1.1.1/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-closeable-tabs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-closeable-tabs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-closeable-tabs/es/index' {
  declare module.exports: any;
}

declare module 'react-closeable-tabs/lib/index' {
  declare module.exports: any;
}

declare module 'react-closeable-tabs/umd/react-closeable-tabs' {
  declare module.exports: any;
}

declare module 'react-closeable-tabs/umd/react-closeable-tabs.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-closeable-tabs/es/index.js' {
  declare module.exports: $Exports<'react-closeable-tabs/es/index'>;
}
declare module 'react-closeable-tabs/lib/index.js' {
  declare module.exports: $Exports<'react-closeable-tabs/lib/index'>;
}
declare module 'react-closeable-tabs/umd/react-closeable-tabs.js' {
  declare module.exports: $Exports<'react-closeable-tabs/umd/react-closeable-tabs'>;
}
declare module 'react-closeable-tabs/umd/react-closeable-tabs.min.js' {
  declare module.exports: $Exports<'react-closeable-tabs/umd/react-closeable-tabs.min'>;
}
