// flow-typed signature: b2426f76f08e06654f5352c2c231d812
// flow-typed version: <<STUB>>/serialport_v^7.1.4/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'serialport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'serialport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'serialport/lib/index' {
  declare module.exports: any;
}

declare module 'serialport/lib/parsers' {
  declare module.exports: any;
}

declare module 'serialport/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'serialport/lib/index.js' {
  declare module.exports: $Exports<'serialport/lib/index'>;
}
declare module 'serialport/lib/parsers.js' {
  declare module.exports: $Exports<'serialport/lib/parsers'>;
}
declare module 'serialport/test.js' {
  declare module.exports: $Exports<'serialport/test'>;
}
