// flow-typed signature: fe9215969a659113f51c562f4189fb74
// flow-typed version: <<STUB>>/sql.js_v^0.4.0/flow_v0.77.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sql.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sql.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sql.js/gh-pages/documentation/javascript/application' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/documentation/javascript/search' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/GUI/codemirror/lib/codemirror' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/GUI/codemirror/mode/sql/sql' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/GUI/gui' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/api' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/shell-post' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/shell-pre' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/sql-debug' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/sql-optimized' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/sql' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/worker' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/js/worker.sql' {
  declare module.exports: any;
}

declare module 'sql.js/gh-pages/performance' {
  declare module.exports: any;
}

declare module 'sql.js/js/api' {
  declare module.exports: any;
}

declare module 'sql.js/js/shell-post' {
  declare module.exports: any;
}

declare module 'sql.js/js/shell-pre' {
  declare module.exports: any;
}

declare module 'sql.js/js/sql-debug' {
  declare module.exports: any;
}

declare module 'sql.js/js/sql-memory-growth' {
  declare module.exports: any;
}

declare module 'sql.js/js/sql' {
  declare module.exports: any;
}

declare module 'sql.js/js/worker' {
  declare module.exports: any;
}

declare module 'sql.js/js/worker.sql' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sql.js/gh-pages/documentation/javascript/application.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/documentation/javascript/application'>;
}
declare module 'sql.js/gh-pages/documentation/javascript/search.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/documentation/javascript/search'>;
}
declare module 'sql.js/gh-pages/GUI/codemirror/lib/codemirror.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/GUI/codemirror/lib/codemirror'>;
}
declare module 'sql.js/gh-pages/GUI/codemirror/mode/sql/sql.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/GUI/codemirror/mode/sql/sql'>;
}
declare module 'sql.js/gh-pages/GUI/gui.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/GUI/gui'>;
}
declare module 'sql.js/gh-pages/js/api.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/api'>;
}
declare module 'sql.js/gh-pages/js/shell-post.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/shell-post'>;
}
declare module 'sql.js/gh-pages/js/shell-pre.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/shell-pre'>;
}
declare module 'sql.js/gh-pages/js/sql-debug.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/sql-debug'>;
}
declare module 'sql.js/gh-pages/js/sql-optimized.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/sql-optimized'>;
}
declare module 'sql.js/gh-pages/js/sql.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/sql'>;
}
declare module 'sql.js/gh-pages/js/worker.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/worker'>;
}
declare module 'sql.js/gh-pages/js/worker.sql.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/js/worker.sql'>;
}
declare module 'sql.js/gh-pages/performance.js' {
  declare module.exports: $Exports<'sql.js/gh-pages/performance'>;
}
declare module 'sql.js/js/api.js' {
  declare module.exports: $Exports<'sql.js/js/api'>;
}
declare module 'sql.js/js/shell-post.js' {
  declare module.exports: $Exports<'sql.js/js/shell-post'>;
}
declare module 'sql.js/js/shell-pre.js' {
  declare module.exports: $Exports<'sql.js/js/shell-pre'>;
}
declare module 'sql.js/js/sql-debug.js' {
  declare module.exports: $Exports<'sql.js/js/sql-debug'>;
}
declare module 'sql.js/js/sql-memory-growth.js' {
  declare module.exports: $Exports<'sql.js/js/sql-memory-growth'>;
}
declare module 'sql.js/js/sql.js' {
  declare module.exports: $Exports<'sql.js/js/sql'>;
}
declare module 'sql.js/js/worker.js' {
  declare module.exports: $Exports<'sql.js/js/worker'>;
}
declare module 'sql.js/js/worker.sql.js' {
  declare module.exports: $Exports<'sql.js/js/worker.sql'>;
}
